### ISSUE TITLE
Build broken on macOS

### ISSUE THREAD

**Issue by NattyNarwhal** [rpm-software-management/drpm#23]
I'm building drpm so I can build createrepo-c on macOS. Two build issues though:

1. `sys/sysmacros.h` is defined when it shouldn't be. I'm using this crude hack, but it should be fixed as a CMake level check:
```diff
diff --git a/src/drpm_block.c b/src/drpm_block.c
index c5607da..f39754b 100644
--- a/src/drpm_block.c
+++ b/src/drpm_block.c
@@ -22,7 +22,9 @@
 #include "drpm.h"
 #include "drpm_private.h"
 
+#ifndef __APPLE__
 #include <sys/sysmacros.h>
+#endif
 
 #include <stdint.h>
 #include <stdbool.h>
diff --git a/src/drpm_make.c b/src/drpm_make.c
index 00d2f10..d6f7db3 100644
--- a/src/drpm_make.c
+++ b/src/drpm_make.c
@@ -22,7 +22,9 @@
 #include "drpm.h"
 #include "drpm_private.h"
 
+#ifndef __APPLE__
 #include <sys/sysmacros.h>
+#endif
 
 #include <stdio.h>
 #include <stdint.h>
```
2. `_DARWIN_C_SOURCE` (or lack of `_POSIX_C_SOURCE`) must be defined to make `major`/`minor` visible.

**Comment by kontura** [comment]
Unfortunately I don't really have a way to work on this on macOS.

But if you (or anyone else) creates a PR that would be great.

**Comment by kontura** [comment]
I am closing this for now but like I said PRs welcome!
