### ISSUE TITLE
re-license drpm under LGPLv2+

### ISSUE THREAD

**Issue by dmach** [rpm-software-management/drpm#4]
@Conan-Kudo requested license change from LGPLv3+ to LGPLv2+.
Some projects need more permissive license.

I can speak for the Red Hat's  Software Management team that runs this github org and maintains the project - and from that perspective, I support re-licensing.

@matejchalk @kontura @Conan-Kudo @pmatilai - you all have contributed to the drpm project. Are you fine with re-licensing under LGPLv2+?

**Comment by Conan-Kudo** [comment]
I'm good with a relicense.

**Comment by matejchalk** [comment]
I'm OK with this.

**Comment by pmatilai** [comment]
Fine with me too.

**Comment by kontura** [comment]
Fine by me as well.

**Comment by Conan-Kudo** [comment]
Done with d46b26e6d71fc3f10a74bc913efa2d376105e9c4.
